server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: C:\Users\Arjun\Desktop\Cert\keyStore.p12
    key-store-password: changeit

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee_store
    username: root
    password: xKij7s
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true